version: 1.0.{build}

branches:
  only:
    - main

skip_tags: true
skip_commits:
  files:
    - README.md
    - .github/*
    - docs/*

max_jobs: 1

image: Visual Studio 2019

clone_folder: c:\projects\gibbed-tacticsogre

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
# - choco install dotnetcore-sdk --pre -y -r
  - git submodule update --init --recursive

configuration:
  - Debug

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  project: Tactics Ogre.sln
  parallel: true
  verbosity: minimal

before_build:
  - nuget restore

after_build:
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt taco_%APPVEYOR_BUILD_VERSION%.zip                    ./LICENSE.txt ./README.txt git-log.txt configs bin/Gibbed.*.exe bin/*.dll
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt taco_%APPVEYOR_BUILD_VERSION%_with-debug-symbols.zip ./LICENSE.txt ./README.txt git-log.txt configs bin/Gibbed.*.exe bin/*.dll bin/Gibbed.*.pdb NDesk.Options.pdb Tommy*.pdb

artifacts:
  - path: '*.zip'
